### ISSUE TITLE
Add Complex Pedigree Examples

### ISSUE THREAD

**Issue by liberaliscomputing** [GA4GH-Pedigree-Standard/pedigree-fhir-ig#4]
The current IG includes easy-to-understand example resources of pedigree as follows:

- [Simpson's pedigree](https://ga4gh-cp.github.io/pedigree-fhir-ig/Composition-SimpsonsPedigree.html)
- [The trio's pedigree](https://ga4gh-cp.github.io/pedigree-fhir-ig/Composition-TrioPedigree.html)

Let's also consider adding more complex examples, for example, from the pedigree connectathons.

**Comment by liberaliscomputing** [comment]
Here are three examples distributed by Lindsay for the pedigree connectathons:

- Pedigree 1
![pedigree-1](https://user-images.githubusercontent.com/8662608/114611659-43ef6f00-9c6f-11eb-96ed-550eb6e8b186.png)
- Pedigree 2
![pedigree-2](https://user-images.githubusercontent.com/8662608/114611737-59fd2f80-9c6f-11eb-915d-c34d1a9febf0.png)
- Pedigree 3
![pedigree-3](https://user-images.githubusercontent.com/8662608/114611788-62ee0100-9c6f-11eb-9c71-8130235df786.png)

**Comment by liberaliscomputing** [comment]
@ametke, once the new FSH resources organization get merged, I will start to add these examples!

**Comment by ametke** [comment]
Great, thanks @liberaliscomputing!
